export const OSM_CATEGORIES: Record<string, { key: string; value: string }> = {
  'Accounting':        { key: 'office',  value: 'accountant' },
  'Auto Repair':       { key: 'shop',    value: 'car_repair' },
  'Bakery':            { key: 'shop',    value: 'bakery' },
  'Bank':              { key: 'amenity', value: 'bank' },
  'Bar / Pub':         { key: 'amenity', value: 'bar' },
  'Barbershop':        { key: 'shop',    value: 'hairdresser' },
  'Beauty Salon':      { key: 'shop',    value: 'beauty' },
  'Cafe':              { key: 'amenity', value: 'cafe' },
  'Car Wash':          { key: 'amenity', value: 'car_wash' },
  'Carpenter':         { key: 'craft',   value: 'carpenter' },
  'Clinic / Doctor':   { key: 'amenity', value: 'clinic' },
  'Clothing Store':    { key: 'shop',    value: 'clothes' },
  'Dentist':           { key: 'amenity', value: 'dentist' },
  'Electrician':       { key: 'craft',   value: 'electrician' },
  'Electronics Shop':  { key: 'shop',    value: 'electronics' },
  'Florist':           { key: 'shop',    value: 'florist' },
  'Guest House':       { key: 'tourism', value: 'guest_house' },
  'Gym / Fitness':     { key: 'leisure', value: 'fitness_centre' },
  'Hair Salon':        { key: 'shop',    value: 'hairdresser' },
  'Hotel':             { key: 'tourism', value: 'hotel' },
  'Jeweler':           { key: 'shop',    value: 'jewelry' },
  'Laundry':           { key: 'shop',    value: 'laundry' },
  'Law Firm':          { key: 'office',  value: 'lawyer' },
  'Optician':          { key: 'shop',    value: 'optician' },
  'Petrol Station':    { key: 'amenity', value: 'fuel' },
  'Pharmacy':          { key: 'amenity', value: 'pharmacy' },
  'Place of Worship':  { key: 'amenity', value: 'place_of_worship' },
  'Plumber':           { key: 'craft',   value: 'plumber' },
  'Real Estate':       { key: 'office',  value: 'estate_agent' },
  'Restaurant':        { key: 'amenity', value: 'restaurant' },
  'School':            { key: 'amenity', value: 'school' },
  'Spa / Massage':     { key: 'leisure', value: 'spa' },
  'Supermarket':       { key: 'shop',    value: 'supermarket' },
  'Veterinary':        { key: 'amenity', value: 'veterinary' },
}

export const CATEGORY_NAMES = Object.keys(OSM_CATEGORIES).sort()